import CustomCursor from '@/components/CustomCursor';
import Layout from '@/components/Layout';
import '@/styles/globals.scss';
import Head from 'next/head';

export default function App({ Component, pageProps }) {
    return (
        <>
            <Head>
                <title>mhasanjoy - Personal Portfolio</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon/favicon.ico" />
            </Head>
            <CustomCursor />
            <Layout>
                <Component {...pageProps} />
            </Layout>
        </>
    );
}
