import CustomCursor from '@/components/CustomCursor';
import Head from 'next/head';

export default function Home() {
    return (
        <>
            <CustomCursor />
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>
                <p>
                    Lorem ipsum, dolor sit amet consectetur adipisicing elit.
                    Quo ratione eos commodi tempore, at consequatur quibusdam
                    error harum ullam odio sequi. Ullam officiis obcaecati
                    voluptatum laboriosam ea mollitia saepe nulla! Perspiciatis
                    ad dignissimos ducimus maiores officia sit eum facere minima
                    soluta ipsa, quae veniam quo commodi dolorum necessitatibus
                    minus inventore corrupti doloremque est consequatur enim
                    debitis facilis! Quos rerum exercitationem aliquid repellat
                    facilis, error velit minima excepturi eius perferendis
                    ducimus consectetur maiores laborum accusantium natus
                    recusandae, ex sit illo animi quis dolor! A sit ab, dolore
                    reiciendis in recusandae voluptates esse quisquam aut eos,
                    et dolor animi ad deserunt saepe nulla asperiores voluptas
                    obcaecati sunt quis impedit reprehenderit? Deserunt neque
                    ratione error facilis quis veniam sapiente dolores fuga
                    consequatur cumque, laboriosam nostrum, delectus voluptatum
                    velit dolorum accusamus tempore perspiciatis laborum magni
                    enim architecto fugiat dolore? Eligendi veritatis sunt vero,
                    accusantium doloribus aliquam atque iusto dolores dolorum
                    aspernatur iste perferendis, sapiente debitis harum? Velit
                    sapiente, ex iste inventore, officia consequuntur fuga
                    repellendus quae dolore quaerat sequi nobis amet dolorem
                    illum delectus exercitationem id voluptatem libero nemo
                    molestiae quo facere voluptate. Eaque similique aperiam,
                    voluptates ea voluptas, dolorem expedita eum neque illum
                    deserunt minus. Deserunt pariatur temporibus, qui at hic
                    possimus minus tempore libero sunt nesciunt ipsa a eligendi
                    magni voluptatibus soluta perferendis aliquam molestias
                    quasi quo obcaecati nihil vel quibusdam sed amet. Ullam
                    dolorem fuga porro provident tempore, in explicabo
                    repudiandae a ut nemo nihil vitae quo debitis facilis quas
                    tempora sapiente? Beatae sequi labore aliquam veniam modi
                    obcaecati excepturi eum similique, illo nihil iure quasi,
                    libero mollitia rerum minus exercitationem cum. Harum
                    recusandae reprehenderit dolorem, ipsam reiciendis cum
                    deserunt? Molestias, officia culpa beatae consectetur
                    repellat sit temporibus porro aliquam esse autem? Ipsam
                    numquam nobis similique inventore doloremque, non quaerat
                    voluptatum quo maxime molestias tempore et ad iusto hic vel
                    reprehenderit quae, quos consequuntur dolore quis tenetur?
                    Natus suscipit doloribus ipsum commodi hic similique.
                    Quisquam a eius esse animi reprehenderit deleniti corrupti
                    atque, hic libero magni natus quia accusamus at fugit
                    recusandae. Corporis maxime eius beatae provident totam.
                    Molestias hic, dolore doloremque qui, sit expedita inventore
                    libero praesentium saepe perferendis minus similique id
                    blanditiis veritatis minima, iusto nulla provident nostrum.
                    Adipisci nam blanditiis quidem magnam temporibus esse ut
                    consequuntur explicabo earum ullam, quo delectus nihil,
                    autem ex enim, molestiae sed tempora vitae fuga tempore
                    doloribus nesciunt ad deleniti? Ipsa nisi repellendus,
                    ducimus architecto, alias rerum eos enim adipisci sit
                    explicabo, velit deserunt aliquam at nesciunt qui doloremque
                    ipsam ullam voluptas fugit aut voluptates non. Maxime
                    laudantium qui, magnam libero consequatur voluptatem
                    explicabo sapiente eius reiciendis quod eaque voluptatibus
                    sint, dignissimos fugit consequuntur delectus pariatur sed,
                    accusamus harum quis. Voluptas cumque pariatur odit nemo
                    nihil repellendus quibusdam commodi, molestias excepturi.
                    Odit quaerat laudantium minus suscipit itaque distinctio
                    ducimus, consequatur repellat minima vitae, voluptates
                    praesentium commodi asperiores quam soluta est nisi
                    obcaecati autem sequi amet excepturi. Nostrum officiis
                    cumque debitis sint, voluptatibus dolores fuga facilis odio
                    voluptatem rerum voluptates repellendus fugiat tenetur
                    aspernatur animi facere voluptatum corporis minima expedita
                    sapiente vero eveniet ducimus libero? Omnis rem velit cum
                    harum. Suscipit, adipisci animi officiis consequatur ipsa
                    numquam autem voluptatibus nisi aperiam voluptas culpa
                    aliquam debitis odit distinctio vel quo est iusto molestias
                    asperiores, dolores molestiae, tempora velit. Quibusdam
                    repellendus atque unde consectetur vel, consequuntur veniam
                    totam culpa blanditiis molestiae nostrum quis autem quos
                    architecto eaque at iusto impedit sed. Similique facilis rem
                    neque sint nesciunt repellat aliquam non, maxime molestias
                    omnis quaerat? Perferendis quaerat quod ea minima,
                    asperiores pariatur iste et cum possimus quibusdam nisi vel
                    culpa, tenetur animi nihil eum eos voluptatem quasi labore
                    dolor sit cumque enim ad dicta? Aut architecto eveniet autem
                    fugit suscipit rem possimus eligendi ullam ipsum ratione,
                    quo, reprehenderit quibusdam qui tempora beatae amet
                    voluptatibus aliquid! Sunt odio, adipisci nostrum soluta
                    dolores consequuntur qui fugit, molestias officia vero optio
                    quod. Pariatur autem sequi sunt dolorem illo enim
                    blanditiis, velit obcaecati non expedita excepturi aut a
                    impedit veritatis assumenda id odit! Modi maxime voluptate
                    consectetur ad qui expedita recusandae. Exercitationem, quia
                    adipisci nisi corporis sint perspiciatis voluptatem dolores
                    excepturi itaque totam error ut ad quasi consequuntur.
                    Voluptatibus eveniet cumque natus officiis vel voluptate
                    quibusdam neque id, quod odio dolor error delectus sed vitae
                    eum praesentium, quis nihil eaque, debitis itaque sint
                    soluta architecto veniam. Numquam error tenetur
                    exercitationem in atque, iste eveniet aliquam, veniam
                    possimus deserunt maiores impedit sapiente optio quo quos
                    rerum tempora recusandae quisquam reprehenderit ea. Velit
                    autem labore, nostrum excepturi cum ut, possimus beatae
                    ratione praesentium libero consequuntur illo doloremque
                    tempora accusantium aliquid reiciendis? Nesciunt amet
                    corrupti mollitia sunt harum nemo deserunt libero possimus
                    maxime doloribus alias illum vitae, dolorem aut. Tempore
                    illo magnam labore amet dolorum minima sunt, aperiam eaque,
                    et similique consequatur possimus veritatis ipsa laborum
                    aspernatur. Dolorem, doloribus ducimus! A laudantium rerum
                    doloribus laborum tempora libero optio molestias nesciunt ut
                    consequatur delectus ad vel odio assumenda vero soluta,
                    quisquam accusamus est ipsam exercitationem reprehenderit
                    necessitatibus unde corrupti? Ab, quisquam. Consequatur
                    commodi consequuntur repellendus minima officiis pariatur
                    error expedita ad, quia eveniet deleniti distinctio dolores
                    accusantium quas, culpa atque iste fuga, quo dolor porro
                    voluptatem voluptates. Non, optio quos sit officia suscipit
                    velit! Dolore id consectetur, quam laboriosam, sit vitae aut
                    cum repellendus aliquam ratione neque quis earum commodi
                    saepe nihil nobis excepturi quasi dignissimos temporibus
                    dolorem? Dolor sint officiis, facilis vitae eos perspiciatis
                    minima aspernatur assumenda magnam. Incidunt nulla vel fugit
                    ullam ducimus, omnis porro molestias odit doloremque magnam,
                    minima ipsa aut quis ratione quisquam quaerat explicabo
                    perspiciatis corrupti sint non tempore optio! Architecto
                    quod sequi deserunt rerum accusantium ullam, quia mollitia
                    corporis! Eius ea eveniet tenetur expedita laudantium facere
                    consequuntur non ratione aspernatur reiciendis, fugiat, odit
                    harum ipsa quo delectus nobis sint reprehenderit hic
                    distinctio quos error iusto magni esse? Unde mollitia
                    veritatis porro, necessitatibus illo ut fugiat assumenda sed
                    officiis quas exercitationem vel, rem quia obcaecati dolorum
                    sequi numquam. Rerum, praesentium nihil exercitationem nobis
                    cum dolor? Doloremque deleniti saepe tenetur, rem voluptate
                    quos perferendis! Quidem unde possimus quam, illo facilis
                    officiis deserunt quod dolores tempore iusto voluptas nisi?
                    Minus, doloribus velit!
                </p>
            </div>
        </>
    );
}
